In [1]:
from train import *
import pandas as pd
import numpy as np
import pickle
from apputil import predict_rating

In [2]:
model_1 = pickle.load(open("model_1.pickle", "rb"))

In [3]:
dtr = pickle.load(open("model_2.pickle", "rb"))

In [4]:
# Test with only 100g_USD
df_test_1 = pd.DataFrame({"100g_USD": [8.5, 12.0, 20.0]})
model_1.predict(df_test_1)

array([93.08482397, 93.2091997 , 93.49348707])

In [5]:
df_X = pd.DataFrame([
    [10.00, 1],
    [15.00, 3],
    [8.50, np.nan]
], columns=["100g_USD", "roast_cat"])

y_pred = dtr.predict(df_X.values)
y_pred

/root/miniconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([92.  , 92.  , 94.25])

EXERCISE 3

In [6]:

df_test_3 = pd.DataFrame([
    [10.00, "Dark"],         # Known roast → uses model_2
    [15.00, "Very Light"],   # Unknown roast → uses model_1
    [8.50, None]             # Missing roast → uses model_1
], columns=["100g_USD", "roast"])

predict_rating(df_test_3)


/root/miniconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(
/root/miniconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/root/miniconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([94.        , 93.31580746, 93.08482397])